# Generated by Django 3.0 on 2019-12-14 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_auto_20191213_1702"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="domain",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="studentsof",
                to="app.Domain",
            ),
        ),
    ]
