# Generated by Django 3.0 on 2019-12-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_auto_20191215_1635"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domain",
            name="description",
            field=models.TextField(max_length=1000),
        ),
    ]
