# Generated by Django 3.0.1 on 2019-12-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="OtherInfo",
            field=models.TextField(
                help_text="What You are specifically looking for here?",
                max_length=200,
                null=True,
            ),
        ),
    ]
